# Generated by Django 4.2.25 on 2025-11-17 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_application_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('flag', models.URLField(blank=True, help_text='URL to flag image (or use media upload later)')),
                ('description', models.TextField(blank=True)),
                ('cost_of_living_monthly', models.CharField(blank=True, help_text="e.g. 'USD 1,200 - 2,000 / month'", max_length=80)),
                ('visa_requirements', models.TextField(blank=True)),
                ('typical_tuition_per_year', models.CharField(blank=True, help_text='Country-level tuition range', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=240)),
                ('website', models.URLField(blank=True)),
                ('ranking', models.CharField(blank=True, max_length=80)),
                ('tuition_per_year', models.CharField(blank=True, max_length=80)),
                ('logo', models.URLField(blank=True, help_text='URL to logo image (or upload later)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='myapp.country')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('amount', models.CharField(blank=True, max_length=120)),
                ('link', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='myapp.country')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='myapp.university')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('duration', models.CharField(blank=True, help_text="e.g. '1-2 years'", max_length=80)),
                ('overview', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='myapp.country')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='myapp.university')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
