# Generated by Django 4.2.25 on 2025-11-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_country_university_scholarship_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='country',
        ),
        migrations.RemoveField(
            model_name='course',
            name='university',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='country',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='university',
        ),
        migrations.AlterUniqueTogether(
            name='university',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='university',
            name='country',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Scholarship',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
