# Generated by Django 4.2.25 on 2025-12-05 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_writingnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('filename', models.CharField(help_text='Relative static path, e.g. audio/CGtoIELTS_01.mp3', max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=50)),
                ('passage_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WritingTask1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WritingTask2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='myapp.readingpassage')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('qtype', models.CharField(choices=[('mcq', 'Multiple choice'), ('fill', 'Fill in the blank'), ('short', 'Short answer')], default='short', max_length=10)),
                ('options', models.TextField(blank=True, help_text='For MCQ: newline separated options')),
                ('correct_answer', models.CharField(help_text='For mcq store the exact option text. For fill/short store canonical answer (lowercase).', max_length=512)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='myapp.listeningaudio')),
            ],
        ),
    ]
