# Generated by Django 4.2.25 on 2025-12-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
