# Generated by Django 4.2.25 on 2025-12-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('superstudent', 'Super Student')], default='student', max_length=20),
        ),
    ]
